"""baseline

Revision ID: 001_baseline
Revises:
Create Date: 2026-09-27 20:48:46.871002
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_table('equipment',
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_serial_number'), 'equipment', ['serial_number'], unique=False)
    op.create_index(op.f('ix_equipment_tenant_id'), 'equipment', ['tenant_id'], unique=False)
    op.create_table('reports',
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('parts_needed', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_equipment_id'), 'reports', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('fallas',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('parte', sa.String(length=200), nullable=False),
    sa.Column('pieza', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('causa_raiz', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fallas_equipment_id'), 'fallas', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_fallas_tenant_id'), 'fallas', ['tenant_id'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('falla_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('subtotal_refacciones', sa.Float(), nullable=False),
    sa.Column('mano_de_obra', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['falla_id'], ['fallas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_equipment_id'), 'cotizaciones', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_falla_id'), 'cotizaciones', ['falla_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_tenant_id'), 'cotizaciones', ['tenant_id'], unique=False)
    op.create_table('falla_fotos',
    sa.Column('falla_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['falla_id'], ['fallas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_falla_fotos_falla_id'), 'falla_fotos', ['falla_id'], unique=False)
    op.create_index(op.f('ix_falla_fotos_tenant_id'), 'falla_fotos', ['tenant_id'], unique=False)
    op.create_table('refacciones',
    sa.Column('falla_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('numero_parte', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('precio_confirmado', sa.Boolean(), nullable=False),
    sa.Column('editado_por_mecanico', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['falla_id'], ['fallas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refacciones_falla_id'), 'refacciones', ['falla_id'], unique=False)
    op.create_index(op.f('ix_refacciones_tenant_id'), 'refacciones', ['tenant_id'], unique=False)
    op.create_table('reportes_cliente',
    sa.Column('falla_id', sa.UUID(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['falla_id'], ['fallas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_cliente_falla_id'), 'reportes_cliente', ['falla_id'], unique=False)
    op.create_index(op.f('ix_reportes_cliente_tenant_id'), 'reportes_cliente', ['tenant_id'], unique=False)
    op.create_table('procedimientos_reparacion',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('falla_id', sa.UUID(), nullable=True),
    sa.Column('cotizacion_id', sa.UUID(), nullable=True),
    sa.Column('mecanico_id', sa.UUID(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('tiempo_total_horas', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['falla_id'], ['fallas.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedimientos_reparacion_equipment_id'), 'procedimientos_reparacion', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_procedimientos_reparacion_falla_id'), 'procedimientos_reparacion', ['falla_id'], unique=False)
    op.create_index(op.f('ix_procedimientos_reparacion_tenant_id'), 'procedimientos_reparacion', ['tenant_id'], unique=False)
    op.create_table('pasos_reparacion',
    sa.Column('procedimiento_id', sa.UUID(), nullable=False),
    sa.Column('numero_paso', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tiempo_minutos', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['procedimiento_id'], ['procedimientos_reparacion.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasos_reparacion_procedimiento_id'), 'pasos_reparacion', ['procedimiento_id'], unique=False)
    op.create_index(op.f('ix_pasos_reparacion_tenant_id'), 'pasos_reparacion', ['tenant_id'], unique=False)
    op.create_table('paso_fotos',
    sa.Column('paso_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paso_id'], ['pasos_reparacion.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paso_fotos_paso_id'), 'paso_fotos', ['paso_id'], unique=False)
    op.create_index(op.f('ix_paso_fotos_tenant_id'), 'paso_fotos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Proteccion del piso permanente: el baseline es la historia minima.
    # Un 'alembic downgrade base' borraria las 13 tablas de negocio, por lo
    # que NO se soporta downgrade por debajo de 001_baseline. Las migraciones
    # futuras (002 -> 001, 003 -> 002, ...) siguen siendo reversibles con
    # normalidad porque su downgrade() no toca este archivo.
    raise RuntimeError(
        "Downgrade no soportado por debajo del baseline (001_baseline). "
        "Este revision define el piso del esquema; revertirlo eliminaria las "
        "13 tablas de negocio. Para entornos vacios use 'alembic upgrade head'."
    )
